package com.soapsoft.Vista.Model;
// Generated 25/11/2017 12:16:48 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbDetalleFacturaVenta generated by hbm2java
 */

public class DetalleFacturaVenta  implements java.io.Serializable {
    
     private Integer id;
     private int idFacturaVenta;
     private int idProductoTerminado;
     private int cantidad;
     private int vlorIva;
     private String tipoIva;
     private int vlorUnitario;
     private int vlorTotal;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;

    public DetalleFacturaVenta(Integer id, int idFacturaVenta, int idProductoTerminado, int cantidad, int vlorIva, String tipoIva, int vlorUnitario, int vlorTotal, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn) {
        this.id = id;
        this.idFacturaVenta = idFacturaVenta;
        this.idProductoTerminado = idProductoTerminado;
        this.cantidad = cantidad;
        this.vlorIva = vlorIva;
        this.tipoIva = tipoIva;
        this.vlorUnitario = vlorUnitario;
        this.vlorTotal = vlorTotal;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
        this.modificadoPor = modificadoPor;
        this.modificadoEn = modificadoEn;
    }

    public DetalleFacturaVenta() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdFacturaVenta() {
        return idFacturaVenta;
    }

    public void setIdFacturaVenta(int idFacturaVenta) {
        this.idFacturaVenta = idFacturaVenta;
    }

    public int getIdProductoTerminado() {
        return idProductoTerminado;
    }

    public void setIdProductoTerminado(int idProductoTerminado) {
        this.idProductoTerminado = idProductoTerminado;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public int getVlorIva() {
        return vlorIva;
    }

    public void setVlorIva(int vlorIva) {
        this.vlorIva = vlorIva;
    }

    public String getTipoIva() {
        return tipoIva;
    }

    public void setTipoIva(String tipoIva) {
        this.tipoIva = tipoIva;
    }

    public int getVlorUnitario() {
        return vlorUnitario;
    }

    public void setVlorUnitario(int vlorUnitario) {
        this.vlorUnitario = vlorUnitario;
    }

    public int getVlorTotal() {
        return vlorTotal;
    }

    public void setVlorTotal(int vlorTotal) {
        this.vlorTotal = vlorTotal;
    }

    public String getCreadoPor() {
        return creadoPor;
    }

    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }

    public Date getCreadoEn() {
        return creadoEn;
    }

    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }

    public String getModificadoPor() {
        return modificadoPor;
    }

    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    public Date getModificadoEn() {
        return modificadoEn;
    }

    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }

      
     

}


